import type { Metadata } from 'next'
import { Fraunces } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'

const fraunces = Fraunces({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={fraunces.className}>
        <Header />
        <main className="px-8">{children}</main>
      </body>
    </html>
  )
}
